# Compose file for setting everything up
# NB
# You need to make passwords for both DBs and distribute them through this
# file appropriately

playerdb:
    name: player_db
    build: player_database
    detach: true
    environment:
        DB_PASSWORD: FuEm7l003bfd6zM

tournamentdb:
    name: tournament_db
    build: tournament_database
    detach: true
    environment:
        DB_PASSWORD: hB2x8avSMNnvCK4T

webserver:
    name: webserver
    build: webserver
    ports:
     - 5000:5000
    links:
     - playerdb:player_db
     - tournamentdb:tournament_db
    detach: true
    environment:
        PLAYER_DB_PASSWORD: FuEm7l003bfd6zM
        TOURNAMENT_DB_PASSWORD: hB2x8avSMNnvCK4T

smoketest:
    build: smoketester
    links:
     - playerdb:player_db
     - tournamentdb:tournament_db
     - webserver
    environment:
        PLAYER_DB_PASSWORD: FuEm7l003bfd6zM
        TOURNAMENT_DB_PASSWORD: hB2x8avSMNnvCK4T

behat:
    build: behat
    links:
     - webserver

